### ISSUE TITLE
difference to waterlinks implementation

### ISSUE THREAD

**Issue by alexanderadam** [TobiasGSmollett/timecop.cr#1]
I just wanted to know whether there are any different aims you have for your implementation as the [implementation of waterlink](https://github.com/waterlink/timecop.cr).

**Comment by tobyapi** [comment]
@alexanderadam I didn't know his timecop.cr repository when I start this project.
Two differences are between this and his timecop.cr:
1. My timecop.cr support nesting of Time.freeze.
Following code will not run on the his timecop.cr:
```crystal
t = Time.new(2008, 10, 10, 10, 10, 10).to_local
Timecop.freeze(t) do
  true.should eq(t == Time.now)
  t2 = Time.new(2008, 9, 9, 9, 9, 9).to_local
  Timecop.freeze(t2) do
    true.should eq(t2 == Time.now)
  end
  true.should eq(t == Time.now)
end
false.should eq(t == Time.now)
```
To run this code, we need using a stack of Time class wrapper in timecop.cr.

2. Last commit in his project is 9 months ago, but some functions are not implemented. I'm going to implement Time.travel and Time.scale by 9/15.

**Comment by alexanderadam** [comment]
Wow, thank you for your fast response!
