### ISSUE TITLE
Time changed by 0.0001 second

### ISSUE THREAD

**Issue by coderhs** [TobiasGSmollett/timecop.cr#2]
I am using timecop in the this project https://github.com/hugoabonizio/schedule.cr/pull/5

By the time I am calculating the interval the time exceeded by 0.0001 second. Which should not be the case when i am using done right? This is the sepc where it happens. 

```rb
    it "should return 30 seconds when scheduled at 30th second of a minute" do
      time = Time.new(2017, 10, 15, 15, 0, 30)
      Timecop.freeze(time)

      Schedule.calculate_interval(:minute).should eq 30.seconds
    end
```

I should be getting 30 seconds but i am getting 00:00:29.9990000.

I am using `Time.now` inside the `calculate_interval` method.

**Comment by coderhs** [comment]
I am doing, `at_the_end_of_minute` inside that method, could that be breaking it? How do we handle such a case.

**Comment by tobyapi** [comment]
@coderhs Hi, I tried the testing but it succeeded.
